### PR TITLE
CRAFT-2476: Delete source app path when relaunched

### PR DESCRIPTION
**Pull request by jrhodes**
## Description
* https://invisionapp.atlassian.net/browse/CRAFT-2476
* CRAFT-2476: Save the source path we couldn’t remove when the app was translocated and remove it after relaunch when we’re not translocated.

To fix the fact that we can't run the AppleScript script to remove the source app after moving it, we will save the source app's path in `NSUserDefaults` under a new key `com.potionfactory.LetsMove.DeleteSourceAppPath`.

Once CraftManager relaunches without being quarantined and translocated, we have sufficient privileges to remove the original version in `~/Downloads` or wherever the user moved it from.

## Testing
- [ ] 0. Clean the build folder in CraftManager
- [ ] 1. In CraftManager, change the `Podfile` to this specific branch by changing the `LetsMove` pod:
```
pod 'LetsMove', :git => 'git@github.com:InVisionApp/LetsMove.git', :branch => 'CRAFT-2476-delete-source-app'
```
- [ ] 2. Run the `pod install` command for CraftManager
- [ ] 3. Archive a copy of CraftManager
- [ ] 4. Upload the archived copy CraftManager.app to Google Drive and re-download it or add quarantine xattrs by running:
```
xattr -w com.apple.quarantine "0083;5d3f6bda;Safari;9DCD17F9-8C4B-450F-B66D-454A096BF395" /Path/To/CraftManager.app
```
- [ ] 5. Delete your CraftManager preferences so LetsMove will ask to move it again:
`defaults delete com.invisionlabs.CraftManager`
- [ ] 6. Run CraftManager
- [ ] 7. Click "Move" on the LetsMove prompt
- [ ] 8. Verify that the original downloaded build is removed and a new one is running from `/Applications/CraftManager.app`.

### CODE REVIEW

**Review by datinc — APPROVED** [review]
LGTM. However, this worked for me before the fix. Can @sanderberents test on his machine as he was seeing the error

**Review by sanderberents — CHANGES_REQUESTED** [review]
I executed the steps as described, with the exception of:
- I used the debug build, as Archive resulted in a signing error
- I did not upload/download it, but used xattr

When I ran it from Downloads, macOS told me I downloaded it (good), but
- It copied it to Applications. The version I started in Downloads remained there.
- I confirmed it was running the /Applications version.
- I went through Craft Manager's welcome screens. Then I rebooted. It did not start Craft Manager automatically at all.

I then started it manually and confirmed that the "Launch Craft on startup" was checked.

This is on 10.14.5.

Although I did the pod steps exactly as you described, to rule out any mistakes on my part you may want to upload your build to Slack, to make absolutely sure the test is valid (and share it with Ana too).

**Comment by jrhodes** [comment]
@sanderberents Could you try this link? I just made an archived build and uploaded it to Google Drive:

https://drive.google.com/open?id=1AzoMMvqFnYfO3xT33sG-8LlwsMP0_q-4

Just be sure to run `defaults delete com.invisionlabs.CraftManager` before launching so LetsMove will ask you to move again.

**Review by sanderberents — CHANGES_REQUESTED** [review]
Same thing is happening. I'll put the Console output on Slack.

**Pull request closed without merging**
