### PR TITLE
COPPER-669 Ask the user

### PR DESCRIPTION
**Pull request by datinc**
If the app is to be installed into the user application folder, then ask the user if this is what they want.

### CODE REVIEW

**Review by dbainbridge — COMMENTED** [review]
If we say the user should never be installing to ~/Applications folder we can drastically simplify this by only have the last two lines in this function: https://github.com/potionfactory/LetsMove/blob/master/PFMoveApplication.m#L241

**Comment by datinc** [comment]
I agree... however are we 100% sure that we do not want to have the option to install into this directory. I do agree it would be much simpler. @dbainbridge

**Comment by datinc** [comment]
@dbainbridge I talked this over with Saxon and he thinks it is ok to leave the option for allowing the user to install into the ~/Application folder.

**Review by jamztang — APPROVED** [review]
there's a few typo in the comments, say line 297, 301.
Other than that LGTM

**Pull request merged**
